version: "0"
services:
  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - /backend/data/redis_data:/data
  chatbot_backend:
    image: chatbot_backend:latest
    build:
      context: backend
      dockerfile: Dockerfile
    ports:
      - "9001:9000"
      - "9003:9002"
    restart: unless-stopped
    working_dir: /app/src
    environment:
      - OPENAI_API_KEY=${OPENAI_API_KEY}
    volumes:
      - ./backend:/app
  chatbot_frontend:
    image: chatbot_frontend:latest
    build:
      context: frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    restart: unless-stopped
    working_dir: /app
