
PRICE_COLUMNS = ['NOMBRE', 'OTROS NOMBRES', 'PRECIO NORMAL',
                 'PRECIO DESCUENTO VIVOLIFE', 'AHORRO', 'TIPO DE MUESTRA',
                 'OBSERVACIONES', 'TIEMPO DE ENTREGA']

SUM_COLUMMS = ['NOMBRE', 'OTROS NOMBRES', 'PRECIO NORMAL',
               'PRECIO DESCUENTO VIVOLIFE', 'AHORRO', 'OBSERVACIONES',
               'PREPARACION', 'TIPO DE MUESTRA']

CLINICAS_LIST = ['HORARIO MAJADAS', 'HORARIO PORTALES',
                 'HORARIO EL FRUTAL', 'HORARIO AMERICAS',
                 'HORARIO CONDADO', 'HORARIO SAN CRISTOBAL',
                 'HORARIO EXPO 1', 'HORARIO MAJADAS 11']

REDIS_HOST = "redis"
REDIS_PORT = 6382
